### PR TITLE
Minor changes related to default 'main' branch naming

### PR DESCRIPTION
**Pull request by jmckenna**
- also removes one Sphinx warning in the RFC index page

### CODE REVIEW

**Comment by klassenjs** [comment]
Thanks for pointing this out.  But I think there are deeper issues here where these docs are mostly talking about GM2 stuff that isn't current anymore.  I think the real fix might be `rm`

**Comment by klassenjs** [comment]
I wonder if we need to leave any of the GeoMoose 2 developer info available for historical reasons (or if for some reason someone wants to try and do their own thing with it).  I'm torn between never breaking a URL and that leaving it here could confuse someone looking for GeoMoose 3 info.

The equivalent info for GeoMoose 3 is part of the GeoMoose 3 docs.

**Comment by klassenjs** [comment]
What do you think about #15?

**Comment by jmckenna** [comment]
I'm so sorry, that's what I get for trying this on a Friday night ha, I did this to the wrong repository as you said.  Closing.

**Pull request closed without merging**
